#!/bin/bash

# This should result in 6ACA5DD94B1765991A6AB8BCAB10C34F25604D9C0014DF51CEB3AA125881C082
# You may need the to install the pbkdf2 and Crypto.Hash packages for the Python to run.
# In addition, you may need to build the blake2 python package.  See the top of
# tigerkdf.py for more details.

tigerkdf -m64 -M20 -b1024 -B0 -t2 -r4
tigerkdf-ref -m64 -M20 -b1024 -B0 -t2 -r4
python2 tigerkdf.py
