#!/bin/bash

# This should result in 38D4DA6842247EA0C9AE2CADA9A679625B33DC18E0C6561B35765379A1494845
# You may need the to install the pbkdf2 and Crypto.Hash packages for the Python to run.
# In addition, you may need to build the blake2 python package.  See the top of
# tigerkdf.py for more details.

tigerkdf -m64 -M20 -b1024 -t2 -r4
tigerkdf-ref -m64 -M20 -b1024 -t2 -r4
python2 tigerkdf.py
