#!/bin/bash

# This should result in 6FC5D6E0649BD143175EEF65A291855A62213953BD08BFD74E97EBFF1AEF2DBE
# You may need the to install the pbkdf2 and Crypto.Hash packages for the Python to run.
# In addition, you may need to build the blake2 python package.  See the top of
# tigerkdf.py for more details.

tigerkdf -m64 -M3 -b1024 -B0 -t2 -r4
tigerkdf-ref -m64 -M3 -b1024 -B0 -t2 -r4
python2 tigerkdf.py
