#!/bin/bash

# Usage: tigerkdf [OPTIONS]
#     -h hashSize     -- The output derived key length in bytes
#     -p password     -- Set the password to hash
#     -s salt         -- Set the salt.  Salt must be in hexidecimal
#     -g garlic       -- Multiplies memory and CPU work by 2^garlic
#     -m memorySize   -- The ammount of memory to use in KB
#     -M multipliesPerBlock -- The number of sequential multiplies to execute per block
#     -r repetitions  -- A multiplier on the total number of times we hash
#     -t parallelism  -- Parallelism parameter, typically the number of threads
#     -b blockSize    -- Memory hashed in the inner loop at once, in bytes

time ./tigerkdf -g 0 -m $((2048*1024)) -r 1 -t 2 -b 16384
